// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkxJe6BTuhoOLKKLqrKJmXo2JBUebor_Q',
    appId: '1:228833758197:web:ded0fe9ad1dc5abbf76ebc',
    messagingSenderId: '228833758197',
    projectId: 'orin-application',
    authDomain: 'orin-application.firebaseapp.com',
    storageBucket: 'orin-application.firebasestorage.app',
    measurementId: 'G-DDY989M00V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRz1wQ2okXbRNzN4s29zUONuhCGDdhVcA',
    appId: '1:228833758197:android:9139ac4bb8faa968f76ebc',
    messagingSenderId: '228833758197',
    projectId: 'orin-application',
    storageBucket: 'orin-application.firebasestorage.app',
  );
}
